//chatgpt.c contained in file 3201410_Louis_Assignment_2
//C program that prioritzes emails for a company CEO
//Creation Date: 9:05AM, Thursday, September 17, 2026
//Inputs: direct inputs with bash command "./claude < testfile.txt"
/*Outputs: The program outputs email sender, how many emails to be read, subject, date, and next email based on the 
commands used in the text file that is inputted.*/
 //Collaborators: ChatGPT - Free
 //Note: None of the code below is original, it was all generated by ChatGPT - Free
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define MAX_SUBJECT 500
#define MAX_LINE 600

/*
    Each email has:
    - sender category
    - subject
    - date
    - priority based on sender category
    - date value used to compare emails
*/
typedef struct {
    char sender[30];
    char subject[MAX_SUBJECT];
    char date[11];

    int priority;
    int dateValue;
} Email;

/*
    List-based MaxHeap.
    The heap is stored in a dynamically allocated array.
*/
typedef struct {
    Email *emails;
    int size;
    int capacity;
} MaxHeap;


/* ---------------------------------------------------------
   Convert sender category to its priority.

   Higher number = higher priority.
   Boss             = 5
   Subordinate      = 4
   Peer              = 3
   ImportantPerson  = 2
   OtherPerson      = 1
   --------------------------------------------------------- */
int getPriority(const char *sender)
{
    if (strcmp(sender, "Boss") == 0)
        return 5;
    else if (strcmp(sender, "Subordinate") == 0)
        return 4;
    else if (strcmp(sender, "Peer") == 0)
        return 3;
    else if (strcmp(sender, "ImportantPerson") == 0)
        return 2;
    else
        return 1;
}


/* ---------------------------------------------------------
   Convert MM-DD-YYYY into a number that can be compared.

   YYYYMMDD is used so that larger values represent newer
   dates.
   --------------------------------------------------------- */
int getDateValue(const char *date)
{
    int month, day, year;

    sscanf(date, "%d-%d-%d", &month, &day, &year);

    return year * 10000 + month * 100 + day;
}


/* ---------------------------------------------------------
   Return 1 if email1 should appear before email2.
   Return 0 otherwise.

   First compare sender priority.
   If priorities are equal, compare dates.
   Newer date gets higher priority.
   --------------------------------------------------------- */
int higherPriority(Email email1, Email email2)
{
    if (email1.priority > email2.priority)
        return 1;

    if (email1.priority < email2.priority)
        return 0;

    /*
        Same sender category:
        newest email gets priority.
    */
    if (email1.dateValue > email2.dateValue)
        return 1;

    return 0;
}


/* ---------------------------------------------------------
   Initialize the heap.
   --------------------------------------------------------- */
void initializeHeap(MaxHeap *heap)
{
    heap->capacity = 10;
    heap->size = 0;

    heap->emails = malloc(heap->capacity * sizeof(Email));

    if (heap->emails == NULL)
    {
        printf("Memory allocation failed.\n");
        exit(1);
    }
}


/* ---------------------------------------------------------
   Resize the heap when it becomes full.
   --------------------------------------------------------- */
void resizeHeap(MaxHeap *heap)
{
    heap->capacity *= 2;

    Email *newEmails =
        realloc(heap->emails, heap->capacity * sizeof(Email));

    if (newEmails == NULL)
    {
        printf("Memory allocation failed.\n");
        free(heap->emails);
        exit(1);
    }

    heap->emails = newEmails;
}


/* ---------------------------------------------------------
   Swap two emails in the heap.
   --------------------------------------------------------- */
void swapEmails(Email *a, Email *b)
{
    Email temp = *a;
    *a = *b;
    *b = temp;
}


/* ---------------------------------------------------------
   Move an inserted email upward until the MaxHeap property
   is restored.
   --------------------------------------------------------- */
void heapifyUp(MaxHeap *heap, int index)
{
    int parent;

    while (index > 0)
    {
        parent = (index - 1) / 2;

        if (higherPriority(heap->emails[index],
                           heap->emails[parent]))
        {
            swapEmails(&heap->emails[index],
                       &heap->emails[parent]);

            index = parent;
        }
        else
        {
            break;
        }
    }
}


/* ---------------------------------------------------------
   Insert an email into the MaxHeap.
   --------------------------------------------------------- */
void insertEmail(MaxHeap *heap, Email email)
{
    if (heap->size == heap->capacity)
        resizeHeap(heap);

    heap->emails[heap->size] = email;

    heapifyUp(heap, heap->size);

    heap->size++;
}


/* ---------------------------------------------------------
   Move an email downward until the MaxHeap property is
   restored.
   --------------------------------------------------------- */
void heapifyDown(MaxHeap *heap, int index)
{
    int left;
    int right;
    int largest;

    while (1)
    {
        left = 2 * index + 1;
        right = 2 * index + 2;
        largest = index;

        if (left < heap->size &&
            higherPriority(heap->emails[left],
                           heap->emails[largest]))
        {
            largest = left;
        }

        if (right < heap->size &&
            higherPriority(heap->emails[right],
                           heap->emails[largest]))
        {
            largest = right;
        }

        if (largest != index)
        {
            swapEmails(&heap->emails[index],
                       &heap->emails[largest]);

            index = largest;
        }
        else
        {
            break;
        }
    }
}


/* ---------------------------------------------------------
   Remove and return the highest-priority email.

   Returns 1 if an email was removed.
   Returns 0 if the heap is empty.
   --------------------------------------------------------- */
int removeMax(MaxHeap *heap, Email *removedEmail)
{
    if (heap->size == 0)
        return 0;

    *removedEmail = heap->emails[0];

    heap->size--;

    if (heap->size > 0)
    {
        heap->emails[0] = heap->emails[heap->size];

        heapifyDown(heap, 0);
    }

    return 1;
}


/* ---------------------------------------------------------
   Return the highest-priority email without removing it.

   This is needed for NEXT.

   Returns 1 if an email exists.
   Returns 0 if the heap is empty.
   --------------------------------------------------------- */
int peekMax(MaxHeap *heap, Email *email)
{
    if (heap->size == 0)
        return 0;

    *email = heap->emails[0];

    return 1;
}


/* ---------------------------------------------------------
   Free heap memory.
   --------------------------------------------------------- */
void destroyHeap(MaxHeap *heap)
{
    free(heap->emails);
    heap->emails = NULL;
    heap->size = 0;
    heap->capacity = 0;
}


/* ---------------------------------------------------------
   Create an Email from the three input fields.
   --------------------------------------------------------- */
Email createEmail(char *sender, char *subject, char *date)
{
    Email email;

    strcpy(email.sender, sender);
    strcpy(email.subject, subject);
    strcpy(email.date, date);

    email.priority = getPriority(sender);
    email.dateValue = getDateValue(date);

    return email;
}


/* ---------------------------------------------------------
   Main program
   --------------------------------------------------------- */
int main(void)
{
    MaxHeap heap;

    char line[MAX_LINE];

    initializeHeap(&heap);

    /*
        Used to remember the email displayed by NEXT.

        This allows:
        NEXT
        NEXT

        to display the same email both times.
    */
    Email currentEmail;

    int hasCurrentEmail = 0;

    while (fgets(line, sizeof(line), stdin) != NULL)
    {
        /*
            Remove newline characters from the input.
        */
        line[strcspn(line, "\r\n")] = '\0';

        /* -------------------------------------------------
           EMAIL command
           ------------------------------------------------- */
        if (strncmp(line, "EMAIL ", 6) == 0)
        {
            char *sender;
            char *subject;
            char *date;

            /*
                The input format is:

                EMAIL sender,subject,date
            */

            sender = line + 6;

            subject = strchr(sender, ',');

            if (subject == NULL)
                continue;

            *subject = '\0';
            subject++;

            date = strchr(subject, ',');

            if (date == NULL)
                continue;

            *date = '\0';
            date++;

            Email email = createEmail(sender, subject, date);

            insertEmail(&heap, email);

            /*
                A new email does not automatically replace the
                currently displayed email. The current email
                remains the result of the most recent NEXT.
            */
        }

        /* -------------------------------------------------
           NEXT command
           ------------------------------------------------- */
        else if (strcmp(line, "NEXT") == 0)
        {
            /*
                If NEXT has already displayed an email and it
                has not been READ, display that same email.

                Otherwise, look at the top of the heap.
            */
            if (!hasCurrentEmail)
            {
                if (peekMax(&heap, &currentEmail))
                {
                    hasCurrentEmail = 1;
                }
            }

            if (hasCurrentEmail)
            {
                printf("Next email:\n");
                printf("Sender: %s\n", currentEmail.sender);
                printf("Subject: %s\n", currentEmail.subject);
                printf("Date: %s\n", currentEmail.date);
            }
        }

        /* -------------------------------------------------
           READ command
           ------------------------------------------------- */
        else if (strcmp(line, "READ") == 0)
        {
            Email removedEmail;

            /*
                READ always removes the highest-priority email.

                This also handles:
                READ
                READ

                because each READ removes the current highest
                priority email independently.
            */
            if (hasCurrentEmail)
            {
                removeMax(&heap, &removedEmail);
                hasCurrentEmail = 0;
            }
            else
            {
                /*
                    If NEXT has not been called, READ still needs
                    to remove the highest-priority email.
                */
                removeMax(&heap, &removedEmail);
            }
        }

        /* -------------------------------------------------
           COUNT command
           ------------------------------------------------- */
        else if (strcmp(line, "COUNT") == 0)
        {
            printf("There are %d emails to read.\n", heap.size);
        }
    }

    destroyHeap(&heap);

    return 0;
}