//claude.c contained in file 3201410_Louis_Assignment_2
//C program that prioritzes emails for a company CEO
//Creation Date: 9:05AM, Thursday, September 17, 2026
//Inputs: direct inputs with bash command "./claude < testfile.txt"
/*Outputs: The program outputs email sender, how many emails to be read, subject, date, and next email based on the 
commands used in the text file that is inputted.*/
 //Collaborators: Claude - Sonnet 5 Medium
 //Note: None of the code below is original, it was all generated by Claude - Sonnet 5 Medium
 //Note2: All comments are human-made by the Author below.
 //Author: Joshua Louis

#include <stdio.h> //standard input/output library
#include <stdlib.h> //standard function library for memory allocation, like malloc, and process control, like exit
#include <string.h> //includes functions for working with strings
#include <ctype.h> //provides functions for classifying and modifying characters

#define MAX_FIELD 128 // max characters for each text field; shrunk from 256 to save memory per email

typedef struct {
    char category[MAX_FIELD];   // sender category text
    char subject[MAX_FIELD];    // subject line text
    char date[MAX_FIELD];       // date text, MM/DD/YYYY
    int  priorityRank;          // numeric rank taken from category
    long dateValue;              // date packed as YYYY/MM/DD for easier comparison
} Email; // one Email structur, one inbox message plus its sort keys

static int categoryRank(const char *category) { // takes the category string, returns its priority number
    if (strcmp(category, "Boss") == 0)            return 5; // Boss is read first
    if (strcmp(category, "Subordinate") == 0)      return 4; // Subordinate is read next
    if (strcmp(category, "Peer") == 0)             return 3; // Peer is read next
    if (strcmp(category, "ImportantPerson") == 0)  return 2; // ImportantPerson is read next
    if (strcmp(category, "OtherPerson") == 0)      return 1; // OtherPerson is read last
    return 0; // unknown category treat as lowest priority of all
}

// Parses "MM-DD-YYYY" into an integer YYYYMMDD. Larger value means newer date and should be read first
static long parseDateValue(const char *date) { // takes date string, returns sortable number
    int mm = 0, dd = 0, yyyy = 0; // temporary holders for month/day/year, default 0 if parsing fails
    sscanf(date, "%d-%d-%d", &mm, &dd, &yyyy); // pull the three numbers out of "MM-DD-YYYY"
    return ((long)yyyy * 10000L) + ((long)mm * 100L) + (long)dd; // combine into one YYYYMMDD-style number
}

// Fills in priorityRank and dateValue for an Email after its category/date strings have been set. 
static void computeEmailKeys(Email *e) { // takes a pointer to an Email so it can modify it directly
    e->priorityRank = categoryRank(e->category); // store the category's numeric rank on the email
    e->dateValue = parseDateValue(e->date);       // store the date's numeric value on the email
}

// Return > 0 if a has strictly higher priority than b, < 0 if lower, and is 0 if they are equal in priority (same category and date).
static int compareEmails(const Email *a, const Email *b) { // compares two emails for heap ordering
    if (a->priorityRank != b->priorityRank) { // if the categories differ in rank,
        return a->priorityRank - b->priorityRank; // higher rank number wins, positive is higher priority
    }
    // Same category: newer date (larger dateValue) wins.
    if (a->dateValue != b->dateValue) { // if same category but different dates
        return (a->dateValue > b->dateValue) ? 1 : -1; // newer date (bigger number) is higher priority
    }
    return 0; // identical priority and date - treat as equal
}

typedef struct { //MaxHeap beginings
    Email *data;      // dynamically allocated array holding the heap's emails
    int    size;       // number of emails currently stored in the heap
    int    capacity;   // total slots currently allocated in data[]
} MaxHeap; // the heap itself, an array plus holding counters

#define HEAP_INITIAL_CAPACITY 16 // how many emails the heap can hold before its first resize

static void heapInit(MaxHeap *h) { // sets up an empty heap, ready to use
    h->capacity = HEAP_INITIAL_CAPACITY; // start with room for 16 emails or whatever the initial capacity is changed to
    h->size = 0; // no emails stored yet
    h->data = (Email *)malloc(sizeof(Email) * h->capacity); // allocate the initial array on the maxheap
    if (h->data == NULL) { // if memory allocation failed and is out of memory
        fprintf(stderr, "Fatal: could not allocate heap memory.\n"); // tell the user what went wrong
        exit(EXIT_FAILURE); // stop the program since we can't continue without memory
    }
}

static void heapFree(MaxHeap *h) { // releases the heap's memory when we're done with it
    free(h->data); // give the array's memory back to the system
    h->data = NULL; // clear the pointer so it's not used by mistake after freeing
    h->size = 0; // reset size for safety
    h->capacity = 0; // reset capacity for safety
}

static void heapGrowIfNeeded(MaxHeap *h) { // doubles the array's size if it's full
    if (h->size >= h->capacity) { // check whether we've run out of room
        h->capacity *= 2; // double the capacity
        Email *newData = (Email *)realloc(h->data, sizeof(Email) * h->capacity); // ask for a bigger block of memory
        if (newData == NULL) { // realloc failed - out of memory
            fprintf(stderr, "Fatal: could not grow heap memory.\n"); // tell the user what went wrong
            exit(EXIT_FAILURE); // stop the program since we can't continue without memory
        }
        h->data = newData; // point the heap at the new array
    }
}

static void swapEmails(Email *a, Email *b) { // swpas the contents of two Email slots
    Email tmp = *a; // copy a's email into a temporary variable
    *a = *b; // overwrite a's slot with b's email
    *b = tmp; // overwrite b's slot with the original a's email
}

static int parentIndex(int i) { return (i - 1) / 2; } // returns the array index of node i's parent
static int leftChildIndex(int i)  { return 2 * i + 1; } // returns the array index of node i's left child
static int rightChildIndex(int i) { return 2 * i + 2; } // returns the array index of node i's right child

// Moves the element at index i up until the max-heap property holds. 
static void siftUp(MaxHeap *h, int i) { // fixes the heap after inserting a new element at index i
    while (i > 0) { // while loop as long as i is greater than 0
        int p = parentIndex(i); // find the current node's parent index
        if (compareEmails(&h->data[i], &h->data[p]) > 0) { // if the child has higher priority than its parent,
            swapEmails(&h->data[i], &h->data[p]); // swap them so the higher priority one moves up
            i = p; // continue checking from the parent's old position
        } else {
            break; // stop
        }
    }
}

// Moves the element at index i down until the max-heap property holds.
static void siftDown(MaxHeap *h, int i) { // fixes the heap after removing the top element
    for (;;) { // loop forever until we break out below
        int left = leftChildIndex(i); // index of the left child
        int right = rightChildIndex(i); // index of the right child
        int largest = i; // assume the current node is the largest for now

        if (left < h->size && compareEmails(&h->data[left], &h->data[largest]) > 0) { // if left child exists and beats current largest
            largest = left; // left child becomes the new largest
        }
        if (right < h->size && compareEmails(&h->data[right], &h->data[largest]) > 0) { // if right child exists and beats current largest
            largest = right; // right child becomes the new largest
        }
        if (largest == i) { // if neither child beat the current node,
            break; // heap property holds here, stop
        }
        swapEmails(&h->data[i], &h->data[largest]); // move the bigger child up into this spot
        i = largest; // continue checking from the child's old position
    }
}

// Inserts a new email into the heap. 
static void heapPush(MaxHeap *h, Email e) { // adds a new email to the heap
    heapGrowIfNeeded(h); // make sure there's room before inserting
    h->data[h->size] = e; // place the new email at the next free slot
    siftUp(h, h->size); // sift it upward until the heap property is restored
    h->size++; // record that the heap now has one more email
}

//Returns a pointer to the highest priority email without removing it. Returns NULL if the heap is empty.
static const Email *heapPeek(MaxHeap *h) { // looks at the top email without removing it
    if (h->size == 0) return NULL; // nothing to peek at if the heap is empty
    return &h->data[0]; // the highest priority email always sits at index 0
}

// Removes and returns the highest priority email. Returns 1 on success, 0 if the heap was empty.
static int heapPop(MaxHeap *h, Email *out) { // removes and returns the top-priority email
    if (h->size == 0) return 0; // nothing to pop if the heap is empty

    if (out != NULL) { // caller wants a copy of the removed email
        *out = h->data[0]; // copy the top email out before we overwrite it
    }

    h->size--; // shrink the size number by one
    h->data[0] = h->data[h->size]; // move the last element into the now-empty root slot
    if (h->size > 0) { // only need to fix the heap if there's still something left
        siftDown(h, 0); // restore the heap property starting from the root
    }
    return 1; // if the pop happened
}

static int heapCount(MaxHeap *h) { return h->size; } // returns how many emails are currently in the heap

// Strips a trailing newline/carriage-return and trailing spaces from a line read via fgets. Parses input, to put it shortly
static void stripLineEnding(char *line) { // removes the newline fgets leaves at the end of a line
    size_t len = strlen(line); // find out how long the line currently is
    while (len > 0 && (line[len - 1] == '\n' || line[len - 1] == '\r')) { // while the last character is a newline or carriage return, carrying cursor back to start
        line[--len] = '\0'; // shrink the string by chopping off that character
    }
}

//Trims leading/trailing whitespace from s, in place.
static void trimWhitespace(char *s) { // removes extra spaces from the front and back of a string
    size_t len = strlen(s); // total length of the string
    size_t start = 0; // will become the index of the first non-space character
    while (start < len && isspace((unsigned char)s[start])) start++; // skip past leading spaces

    size_t end = len; // will become the index just after the last non-space character
    while (end > start && isspace((unsigned char)s[end - 1])) end--; // skips trailing spaces

    size_t newLen = end - start; // length of the trimmed text
    if (start > 0) { // only shift the text if there were leading spaces to remove
        memmove(s, s + start, newLen); // slide the trimmed text to the beginning of the buffer
    }
    s[newLen] = '\0'; // add the new end-of-string marker
}

static int parseEmailFields(const char *rest, Email *e) { // splits "category,subject,date" into the Email struct
    char buffer[1024]; // local working copy of the text so we can safely cut it up
    strncpy(buffer, rest, sizeof(buffer) - 1); // copy the input text into our buffer
    buffer[sizeof(buffer) - 1] = '\0'; // make sure the buffer is always null-terminated

    char *firstComma = strchr(buffer, ','); // find the comma that ends the category field
    if (firstComma == NULL) return 0; // no comma at all means the line is malformed/incorrectly done
    char *secondComma = strchr(firstComma + 1, ','); // find the comma that ends the subject field
    if (secondComma == NULL) return 0; // checking for second missing comma

    *firstComma = '\0'; // cut the string there so "category" is now its own C string
    *secondComma = '\0'; // cut the string there so "subject" is now its own C string

    char *category = buffer; // category text starts at the very beginning of the buffer
    char *subject = firstComma + 1; // subject text starts right after the first comma
    char *date = secondComma + 1; // date text starts right after the second comma

    trimWhitespace(category); // remove any stray spaces around the category
    trimWhitespace(subject); // remove any stray spaces around the subject
    trimWhitespace(date); // remove any stray spaces around the date

    strncpy(e->category, category, MAX_FIELD - 1); // copy the category into the Email struct
    e->category[MAX_FIELD - 1] = '\0'; // guarantee null-termination even if it was truncated
    strncpy(e->subject, subject, MAX_FIELD - 1); // copy the subject into the Email struct
    e->subject[MAX_FIELD - 1] = '\0'; // guarantee null-termination even if it was truncated
    strncpy(e->date, date, MAX_FIELD - 1); // copy the date into the Email struct
    e->date[MAX_FIELD - 1] = '\0'; // guarantee null-termination even if it was truncated

    computeEmailKeys(e); // compute and store the priority rank and date value for sorting
    return 1; // signal that parsing succeeded
}

static void handleEmailCommand(MaxHeap *h, const char *line) { // processes one "EMAIL ..." input line
    //line begins with "EMAIL " (6 characters)
    const char *rest = line + 6; // skip past the "EMAIL " prefix to get to the actual fields
    Email e; // temporary Email to fill in from the parsed text
    if (parseEmailFields(rest, &e)) { // try to parse the category/subject/date fields
        heapPush(h, e); // parsing succeeded, so add the email to the priority queue
    } else {
        // Parsing failed - most likely a missing comma or wrong comma placement.
        printf("Warning: could not parse EMAIL line (check comma placement): %s\n", line); // tell the user which line was bad
    }
}

static void handleNextCommand(MaxHeap *h) { // processes a "NEXT" command
    const Email *top = heapPeek(h); // look at (but don't remove) the highest priority email
    if (top == NULL) { // heap is empty, nothing to show
        printf("No emails to read.\n"); // let the user know there's nothing left
        return; // nothing more to do for this command
    }
    printf("Next email:\n"); // header line for the display
    printf("Sender: %s\n", top->category); // show the sender's category
    printf("Subject: %s\n", top->subject); // show the subject line
    printf("Date: %s\n", top->date); // show the date
}

static void handleReadCommand(MaxHeap *h) { // processes a "READ" command
    /* Pops (deletes) the highest priority email without displaying it,
       whether or not it was previously shown via NEXT. If the heap is
       empty, nothing happens. */
    heapPop(h, NULL); // remove the top email; we don't need its contents, just to delete it
}

static void handleCountCommand(MaxHeap *h) { // processes a "COUNT" command
    int count = heapCount(h); // ask the heap how many emails it currently holds
    printf("There are %d emails to read.\n", count); // display that count to the user
}


int main(void) { // main program 
    MaxHeap heap; // the priority queue that will hold all unread emails
    heapInit(&heap); // set up the heap before we start reading commands

    char line[2048]; // buffer to hold one line of input at a time
    while (fgets(line, sizeof(line), stdin) != NULL) { // read input line by line until end of file
        stripLineEnding(line); // remove the trailing newline character, if any

        if (line[0] == '\0') continue; // ignore empty lines and move to the next one

        if (strncmp(line, "EMAIL ", 6) == 0) { // check if the line starts with EMAIL 
            handleEmailCommand(&heap, line); // hand it off to the EMAIL command handler
        } else if (strcmp(line, "NEXT") == 0) { // check if the line is exactly NEXT
            handleNextCommand(&heap); // hand it off to the NEXT command handler
        } else if (strcmp(line, "READ") == 0) { // check if the line is exactly READ
            handleReadCommand(&heap); // hand it off to the READ command handler
        } else if (strcmp(line, "COUNT") == 0) { // check if the line is exactly COUNT
            handleCountCommand(&heap); // hand it off to the COUNT command handler
        }

    }

    heapFree(&heap); // release the heap's memory before the program exits
    return 0; // signal successful completion to the operating system
}