//claude.c contained in file 3201410_Louis_Assignment_2
//C program that prioritzes emails for a company CEO
//Creation Date: 9:05AM, Thursday, September 17, 2026
//Inputs: direct inputs with bash command "./claude < testfile.txt"
/*Outputs: The program outputs email sender, how many emails to be read, subject, date, and next email based on the 
commands used in the text file that is inputted.*/
 //Collaborators: Claude - Sonnet 5 Medium
 //Note: None of the code below is original, it was all generated by Claude - Sonnet 5 Medium
 //Note2: All comments are human-made by the Author below.
 //Author: Joshua Louis

#include <stdio.h> //standard input/output library
#include <stdlib.h> //standard function library for memory allocation and process control
#include <string.h> //includes functions for working with strings
#include <ctype.h> //provides functions for classifying and modifying characters

#define MAX_FIELD 256 //preprocessor macro, replaces every MAX_FIELD with the number 256

typedef struct { //email record
    char category[MAX_FIELD];   //sender category, e.g. "Boss"
    char subject[MAX_FIELD];    //subject line (may contain spaces)   
    char date[MAX_FIELD];       //date string, MM-DD-YYYY, as given   
    int  priorityRank;          //numeric rank derived from category  
    long dateValue;             //YYYYMMDD style value for comparison 
} Email;


static int categoryRank(const char *category) { //Returns a numeric rank for a sender category. Higher = more urgent. 
    if (strcmp(category, "Boss") == 0)            return 5; //
    if (strcmp(category, "Subordinate") == 0)      return 4; //
    if (strcmp(category, "Peer") == 0)             return 3; //
    if (strcmp(category, "ImportantPerson") == 0)  return 2; //
    if (strcmp(category, "OtherPerson") == 0)      return 1; //
    return 0; //unknown category - treat as lowest priority
}

/* Parses "MM-DD-YYYY" into a comparable integer YYYYMMDD.
 * Larger value == newer date == should be read first (within a tie). */
static long parseDateValue(const char *date) { //
    int mm = 0, dd = 0, yyyy = 0; //
    sscanf(date, "%d-%d-%d", &mm, &dd, &yyyy); //
    return ((long)yyyy * 10000L) + ((long)mm * 100L) + (long)dd; //
}

/* Fills in priorityRank and dateValue for an Email after its
 * category/date strings have been set. */
static void computeEmailKeys(Email *e) { //
    e->priorityRank = categoryRank(e->category); //
    e->dateValue = parseDateValue(e->date); //
}

/* Returns > 0 if a has strictly higher priority than b, < 0 if lower,
 * and 0 if they are equal in priority (same category and date). */
static int compareEmails(const Email *a, const Email *b) { //
    if (a->priorityRank != b->priorityRank) { //
        return a->priorityRank - b->priorityRank; //
    }
    /* Same category: newer date (larger dateValue) wins. */
    if (a->dateValue != b->dateValue) { //
        return (a->dateValue > b->dateValue) ? 1 : -1; //
    }
    return 0; //
}

/* ------------------------------------------------------------------ */
/* MaxHeap - list (array) based implementation, built from scratch     */
/* ------------------------------------------------------------------ */

typedef struct {
    Email *data;     //dynamically allocated array of Emails
    int    size;      //number of emails currently stored
    int    capacity;  //allocated capacity of data[]
} MaxHeap;

#define HEAP_INITIAL_CAPACITY 16 //

static void heapInit(MaxHeap *h) { //
    h->capacity = HEAP_INITIAL_CAPACITY; //
    h->size = 0; //
    h->data = (Email *)malloc(sizeof(Email) * h->capacity); //
    if (h->data == NULL) { //
        fprintf(stderr, "Fatal: could not allocate heap memory.\n"); //
        exit(EXIT_FAILURE); //
    }
}

static void heapFree(MaxHeap *h) { //
    free(h->data); //
    h->data = NULL; //
    h->size = 0; //
    h->capacity = 0; //
}

static void heapGrowIfNeeded(MaxHeap *h) { //
    if (h->size >= h->capacity) { //
        h->capacity *= 2; //
        Email *newData = (Email *)realloc(h->data, sizeof(Email) * h->capacity); //
        if (newData == NULL) { //
            fprintf(stderr, "Fatal: could not grow heap memory.\n"); //
            exit(EXIT_FAILURE); //
        }
        h->data = newData; //
    }
}

static void swapEmails(Email *a, Email *b) { //
    Email tmp = *a; //
    *a = *b; //
    *b = tmp; //
}

static int parentIndex(int i) { return (i - 1) / 2; } //
static int leftChildIndex(int i)  { return 2 * i + 1; } //
static int rightChildIndex(int i) { return 2 * i + 2; } //

/* Moves the element at index i up until the max-heap property holds. */
static void siftUp(MaxHeap *h, int i) { //
    while (i > 0) { //
        int p = parentIndex(i); //
        if (compareEmails(&h->data[i], &h->data[p]) > 0) { //
            swapEmails(&h->data[i], &h->data[p]); //
            i = p; //
        } else { //
            break; //
        }
    }
}

/* Moves the element at index i down until the max-heap property holds. */
static void siftDown(MaxHeap *h, int i) { //
    for (;;) { //
        int left = leftChildIndex(i); //
        int right = rightChildIndex(i); //
        int largest = i; //

        if (left < h->size && compareEmails(&h->data[left], &h->data[largest]) > 0) { //
            largest = left; //
        }
        if (right < h->size && compareEmails(&h->data[right], &h->data[largest]) > 0) { //
            largest = right; //
        }
        if (largest == i) { //
            break; //
        }
        swapEmails(&h->data[i], &h->data[largest]); //
        i = largest; //
    }
}

/* Inserts a new email into the heap. */
static void heapPush(MaxHeap *h, Email e) { //
    heapGrowIfNeeded(h); //
    h->data[h->size] = e; //
    siftUp(h, h->size); //
    h->size++; //
}

/* Returns a pointer to the highest priority email without removing it.
 * Returns NULL if the heap is empty. */
static const Email *heapPeek(MaxHeap *h) { //
    if (h->size == 0) return NULL; //
    return &h->data[0]; //
}

/* Removes and returns the highest priority email.
 * Returns 1 on success (out is filled), 0 if the heap was empty. */
static int heapPop(MaxHeap *h, Email *out) { //
    if (h->size == 0) return 0; //

    if (out != NULL) {
        *out = h->data[0];
    }

    h->size--;
    h->data[0] = h->data[h->size];
    if (h->size > 0) {
        siftDown(h, 0);
    }
    return 1;
}

static int heapCount(MaxHeap *h) {
    return h->size;
}

/* ------------------------------------------------------------------ */
/* Input parsing helpers                                               */
/* ------------------------------------------------------------------ */

/* Strips a trailing newline/carriage-return (and trailing spaces) from
 * a line read via fgets. */
static void stripLineEnding(char *line) {
    size_t len = strlen(line);
    while (len > 0 && (line[len - 1] == '\n' || line[len - 1] == '\r')) {
        line[--len] = '\0';
    }
}

/* Trims leading/trailing whitespace from s, in place. */
static void trimWhitespace(char *s) {
    size_t len = strlen(s);
    size_t start = 0;
    while (start < len && isspace((unsigned char)s[start])) start++;

    size_t end = len;
    while (end > start && isspace((unsigned char)s[end - 1])) end--;

    size_t newLen = end - start;
    if (start > 0) {
        memmove(s, s + start, newLen);
    }
    s[newLen] = '\0';
}

/* Parses the remainder of an EMAIL command line (everything after
 * "EMAIL ") into an Email struct. Fields are comma-delimited:
 *   <category>,<subject>,<date>
 * The subject may contain spaces but not commas. Returns 1 on success,
 * 0 if the line could not be parsed into exactly three fields. */
static int parseEmailFields(const char *rest, Email *e) {
    char buffer[1024];
    strncpy(buffer, rest, sizeof(buffer) - 1);
    buffer[sizeof(buffer) - 1] = '\0';

    char *firstComma = strchr(buffer, ',');
    if (firstComma == NULL) return 0;
    char *secondComma = strchr(firstComma + 1, ',');
    if (secondComma == NULL) return 0;

    *firstComma = '\0';
    *secondComma = '\0';

    char *category = buffer;
    char *subject = firstComma + 1;
    char *date = secondComma + 1;

    trimWhitespace(category);
    trimWhitespace(subject);
    trimWhitespace(date);

    strncpy(e->category, category, MAX_FIELD - 1);
    e->category[MAX_FIELD - 1] = '\0';
    strncpy(e->subject, subject, MAX_FIELD - 1);
    e->subject[MAX_FIELD - 1] = '\0';
    strncpy(e->date, date, MAX_FIELD - 1);
    e->date[MAX_FIELD - 1] = '\0';

    computeEmailKeys(e);
    return 1;
}

/* ------------------------------------------------------------------ */
/* Command handlers                                                    */
/* ------------------------------------------------------------------ */

static void handleEmailCommand(MaxHeap *h, const char *line) {
    /* line begins with "EMAIL " (6 characters) */
    const char *rest = line + 6;
    Email e;
    if (parseEmailFields(rest, &e)) {
        heapPush(h, e);
    }
    /* Malformed EMAIL lines are silently ignored, per input assumption
       that fields will be well-formed. */
}

static void handleNextCommand(MaxHeap *h) {
    const Email *top = heapPeek(h);
    if (top == NULL) {
        printf("No emails to read.\n");
        return;
    }
    printf("Next email:\n");
    printf("Sender: %s\n", top->category);
    printf("Subject: %s\n", top->subject);
    printf("Date: %s\n", top->date);
}

static void handleReadCommand(MaxHeap *h) {
    /* Pops (deletes) the highest priority email without displaying it,
       whether or not it was previously shown via NEXT. If the heap is
       empty, nothing happens. */
    heapPop(h, NULL);
}

static void handleCountCommand(MaxHeap *h) {
    int count = heapCount(h);
    printf("There are %d emails to read.\n", count);
}

/* ------------------------------------------------------------------ */
/* Main                                                                 */
/* ------------------------------------------------------------------ */

int main(void) {
    MaxHeap heap;
    heapInit(&heap);

    char line[2048];
    while (fgets(line, sizeof(line), stdin) != NULL) {
        stripLineEnding(line);

        /* Skip blank lines */
        if (line[0] == '\0') continue;

        if (strncmp(line, "EMAIL ", 6) == 0) {
            handleEmailCommand(&heap, line);
        } else if (strcmp(line, "NEXT") == 0) {
            handleNextCommand(&heap);
        } else if (strcmp(line, "READ") == 0) {
            handleReadCommand(&heap);
        } else if (strcmp(line, "COUNT") == 0) {
            handleCountCommand(&heap);
        }
        /* Unrecognized commands are ignored. */
    }

    heapFree(&heap);
    return 0;
}